### ISSUE TITLE
Switch to PHP8

### ISSUE THREAD

**Issue by lunik1** [lunik1/docker-tt-rss#6]
PHP8 is now supported upstream, so we need to look into migrating

🐙🐙🐙🐙🐙🐙🐙🐙

**Comment by lbouriez** [comment]
Hello, I need to do some more tests and then I will create the PR:
![image](https://user-images.githubusercontent.com/4749766/113803356-5d059680-972a-11eb-9a00-254c6f2b35ac.png)

I did it in my [HomeAssistant addon](https://github.com/lbouriez/addon-tt-rss/blob/master/ttrss/Dockerfile) to start, I will fork your repo this week and do the changes

The DockerFile will be a bit bigger since the official Alpine-nginx is setup with php7...

**Comment by lbouriez** [comment]
@lunik1 
Any idea why I get this:
![image](https://user-images.githubusercontent.com/4749766/113867596-bd252880-977c-11eb-9022-e346a0d7e23f.png)
I am working here: https://github.com/lbouriez/docker-tt-rss

**Comment by lunik1** [comment]
If I had to guess the new base image does not contain `bash`. I'm not sure given the extra container size and maintenance burden that switching to PHP8 before there is an official lsio container for it is worth it, PHP7 is still supported by upstream.

**Comment by lbouriez** [comment]
It was a CRLF issue...
I created the PR, I tested it, it works :)
@lunik1 feel free to review it and let me know if you want some changes

**Comment by lunik1** [comment]
Following the discussion at #9 this will be closed until the lsio container gains php 8 support or tt-rss drops php 8 support.
